apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhine-frontend
  labels:
    app: rhine-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhine-frontend
  template:
    metadata:
      labels:
        app: rhine-frontend
    spec:
      containers:
        - name: rhine-frontend
          image: __DOCKER_REGISTRY__/rhine-frontend:__BUILD_ID__
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_BASE_URL
              value: "__BACKEND_URL__"


---
apiVersion: v1
kind: Service
metadata:
  name: rhine-frontend-service
spec:
  selector:
    app: rhine-frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 80
  type: LoadBalancer