services:
  backend:
    build: ../backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/rhine_db
      - SPRING_DATASOURCE_USERNAME=rhine_user
      - SPRING_DATASOURCE_PASSWORD=rhine_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - rhine-network

  frontend:
    build: ../frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - rhine-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=rhine_db
      - MYSQL_USER=rhine_user
      - MYSQL_PASSWORD=rhine_password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rhine-network

volumes:
  db_data:


networks:
  rhine-network:
    driver: bridge
