services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "5005:5005" # Debug port
    volumes:
      - ../backend:/workspace
      - /workspace/target # Avoid sync conflicts with local machine
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/rhine_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=rhine_user
      - SPRING_DATASOURCE_PASSWORD=rhine_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    networks:
      - rhine-network
    develop:
      watch:
        - action: rebuild
          path: ../backend/src
          target: /workspace/src
        - action: rebuild
          path: ../backend/pom.xml
          target: /workspace/pom.xml

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - rhine-network
    develop:
      watch:
        - action: sync
          path: ../frontend/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ../frontend/package.json
          target: /app/package.json

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=rhine_db
      - MYSQL_USER=rhine_user
      - MYSQL_PASSWORD=rhine_password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rhine-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "rhine_user", "-prhine_password"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  db_data:


networks:
  rhine-network:
    driver: bridge
