all:
  children:
    k3s_cluster:
      hosts:
        52.14.248.199:
          ansible_host: 52.14.248.199
          ansible_user: ubuntu 
          ansible_ssh_private_key_file: /var/jenkins_home/.ssh/rhine-key.pem
