all:
  children:
    k3s_cluster:
      hosts:
        18.188.204.174:
          ansible_host: 18.188.204.174
          ansible_user: ubuntu 
          ansible_ssh_private_key_file: /var/jenkins_home/.ssh/rhine-key.pem
